# Generated by Django 3.2 on 2023-09-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ment',
        ),
    ]
